### ISSUE TITLE
DOOM (WAD Smoosh)

### ISSUE THREAD

**Issue by RoniPunk** [EmeraldCoasttt/BrutalDoomPlatinum#22]
I have issues with DECORATIONS showing when using the WADsmoosh WAD with 4.0 dev.
3.1.1 works fine but since 4.0dev most decorations do not show with WADsmoosh WAD. 

[doom_complete.zip](https://github.com/EmeraldCoasttt/BrutalDoomPlatinum/files/10317499/doom_complete.zip)
(change zip to PK3)

**Comment by yum13241** [comment]
Wadsmooshed pk3s are not legal to distribute.

**Comment by EmeraldCoasttt** [comment]
Can't replicate, primarily use wadsmoosh for development

**Comment by RoniPunk** [comment]
> Wadsmooshed pk3s are not legal to distribute.

Didn't realized I did that....removed

**Comment by RoniPunk** [comment]
OK I figured out the issue. I made a new WADsmoosh without Betray and Sewers (xbox levels) add. It fixed the issues. I am guessing your wadsmoosh didn't have these levels add.
