### ISSUE TITLE
An old bug

### ISSUE THREAD

**Issue by DuyGamerLHB** [EmeraldCoasttt/BrutalDoomPlatinum#24]
I just found this one unintentionally, it was the same bug caused by sprinting and attempting to reload at the same time, most likely when the weapon's magazine is full, I don't know if you can duplicate this on your side

![Screenshot_Doom_20230109_142056](https://user-images.githubusercontent.com/110778501/211258059-12411f1d-5fd8-4c87-913f-fff7cd1fdf1a.png)

Oh and by the way, thanks for fixing the kicking one

**Comment by RoniPunk** [comment]
I also have this issue sometime.

**Comment by mknepper** [comment]
Can confirm.

**Comment by EmeraldCoasttt** [comment]
Fixed, sprinting has been overhauled and this is no longer possible
