### ISSUE TITLE
Level Enhancement System

### ISSUE THREAD

**Issue by RoniPunk** [EmeraldCoasttt/BrutalDoomPlatinum#25]
Extra decorations like oil drums that are able to be shot for health and armor bonus and enemies that are not usually there spawn in maps are not showing up for me. For example E2M3 the Barron of Hell and Cacodemon not spawning in where they use to in 3.1.1. Also the oil drums that can be shot for items along with many other things not working for me.

Oh in version 3.1.1 on map E2M3 the Cacodemon that is suppose to spawn in the the room with the pink lifts does not spawn. The spawn indicator shows but no Cacodemon spawns.  

I am using the official iWAD when testing, not just the WADsmoosh. Both do not work and using gzDOOM 4.10.0.

Keep up the great work. I will let you know if I figure this out.

**Comment by EmeraldCoasttt** [comment]
Not a bug, MES Is in the process of an overhaul
