### ISSUE TITLE
Script error, "BrutalDoomPlatinumv4.0.pk3:cvarinfo.txt" line 277. Unknown cvar attribute 'nosave'

### ISSUE THREAD

**Issue by Korb** [EmeraldCoasttt/BrutalDoomPlatinum#49]
> OS: Windows 8 (or higher) (NT 6.2) Build 9200
> M_LoadDefaults: Load system defaults.
> Using program directory for storage
> W_Init: Init WADfiles.
> adding D:/Doom 2/Zandronum/zandronum.pk3, 696 lumps
> adding D:/Doom 2/Zandronum/doom.wad, 2306 lumps
> adding D:/Doom 2/Zandronum/BrutalDoomPlatinumv4.0.pk3, 23018 lumps
> adding D:/Doom 2/Zandronum/BrutalDoomPlatinumv4.0.pk3:dmlevels.wad, 118 lumps
> adding D:/Doom 2/Zandronum/BrutalDoomPlatinumv4.0.pk3:psxlevels.wad, 42 lumps
> adding D:/Doom 2/Zandronum/BrutalDoomPlatinumv4.0.pk3:testmap.wad, 138 lumps
> adding D:/Doom 2/Zandronum/BrutalDoomPlatinumv4.0.pk3:titlemap.wad, 4 lumps
> Execution could not continue.
> Script error, "BrutalDoomPlatinumv4.0.pk3:cvarinfo.txt" line 277:
> Unknown cvar attribute 'nosave'

Microsoft Windows 10.0.19045.3803

zandronum.exe:
Verified: Unsigned
Link date: 1:37 13.12.2021
Publisher: n/a
Company:
Description: Zandronum
Product: Zandronum
Prod version: 3.1-r211211-2135
File version: v3.1-r211211-2135
MachineType: 64-bit
Binary Version: 3.1.6587.1

**Comment by EmeraldCoasttt** [comment]
Brutal Doom Platinum is not compatible with Zandronum, please use GZDoom version 4.10 or higher
