### ISSUE TITLE
Compatible with Voxel Doom ?

### ISSUE THREAD

**Issue by cde2496** [EmeraldCoasttt/BrutalDoomPlatinum#55]
Does not seem to run the voxel doom sprites.
Only the main player is voxelised.

Link to the voxel doom mod:
https://www.moddb.com/mods/voxel-doom-ii
https://doomwiki.org/wiki/Voxel_Doom

**Comment by litaniast** [comment]
I think Voxel Doom for Brutal Doom and its variants needed 
https://www.moddb.com/mods/brutal-doom/addons/voxel-patch-for-brutal-doom-v21

**Comment by EmeraldCoasttt** [comment]
Voxel doom will never be compatible with platinum, there's way too many assets that would conflict with the voxels
