### ISSUE TITLE
Can't use gamepad to choose modifier

### ISSUE THREAD

**Issue by litaniast** [EmeraldCoasttt/BrutalDoomPlatinum#56]
![modifier](https://github.com/EmeraldCoasttt/BrutalDoomPlatinum/assets/4857928/88ac58c6-54e5-4210-9302-a31e7053aedb)
When I tried to start game with my gamepad, It needs to mouse clicking to choose modifier. Can't pass that for my gamepad.

**Comment by EmeraldCoasttt** [comment]
Closed as duplicate
