### ISSUE TITLE
Dual Revolver Alt fire

### ISSUE THREAD

**Issue by cutting6** [EmeraldCoasttt/BrutalDoomPlatinum#62]
I think it would be cool if the alt fire for the dual revolvers would be like the one in Blood Extra Crispy https://youtu.be/wH8IEja_bcQ?si=Davz4zNz-9Fb4NRL&t=57

**Comment by EmeraldCoasttt** [comment]
That's awesome, I might have to...

**Comment by EmeraldCoasttt** [comment]
Not 1:1 but I did it!

**Comment by cutting6** [comment]
The deadeye ability can be added as the 2nd special action.
