### ISSUE TITLE
Rocket and Grenadelauncher

### ISSUE THREAD

**Issue by PatoPicazzo** [EmeraldCoasttt/BrutalDoomPlatinum#65]
Hello, in the latest dev version, the grenade launcher and rocket launcher appear to be malfunctioning. Let me explain: the grenade launcher's projectile no longer travels long distances when fired, as it did in previous versions, and the rocket launcher no longer has the thermal sight, or if it does, it isn’t working.

**Comment by EmeraldCoasttt** [comment]
The grenade launcher's projectile does not explode until the trigger is released 
The rocket launcher's thermal sight is activated by holding altfire
